[package]
name = "vault_program"
version = "0.1.0"
edition = "2021"

[lib]
name = "vault_program"
crate-type = ["cdylib", "lib"]

[dependencies]
solana-program = "=2.0.11"
borsh = "1.5.1"
thiserror = "1.0.64"
