[package]
name = "vault_program"
version = "0.1.0"
edition = "2021"

[features]
no-entrypoint = []

[lib]
crate-type = ["cdylib", "lib"]
name = "vault_program"

[dependencies]
borsh = "0.10.3"
solana-program = "2"
# drift_interface = { workspace = true }
thiserror = "1.0.64"
