[package]
name = "vault-program"
version = "0.1.0"
edition = "2021"

[features]
no-entrypoint = []

[lib]
crate-type = ["cdylib", "lib"]
name = "vault_program"

[dependencies]
borsh = "1.5.1"
borsh-derive = "1.5.1"
solana-program = "2"
# drift_interface = { workspace = true }
thiserror = "1.0.65"
