[workspace]
members = ["vault-program"]
resolver = "2"

[profile.release]
overflow-checks = true
opt-level = 3
lto = "fat"
strip = "symbols"
debug = false
incremental = false
codegen-units = 1

[workspace.dependencies]

# workspace members
drift_interface = { path = "./deps/drift/drift_interface" }