[workspace]
members = [
    "vault-program",
    "deps/drift/drift_interface",
    ]
resolver = "2"

[profile.release]
overflow-checks = true
opt-level = 3
lto = "fat"
strip = "symbols"
debug = false
incremental = false
codegen-units = 1

[workspace.dependencies]
drift_interface = { path = "./deps/drift/drift_interface" }