[package]
name = "drift_interface"
version = "2.96.0"
edition = "2021"

[dependencies.borsh]
version = "^1.5.1"

[dependencies.num-derive]
version = "^0.3"

[dependencies.num-traits]
version = "^0.2"

[dependencies.serde]
optional = true
version = "^1.0"

[dependencies.solana-program]
version = "^2"

[dependencies.thiserror]
version = "^1.0"
