[package]
name = "pool-program"
version = "0.1.0"
edition = "2021"

[lib]
name = "pool_program"
crate-type = ["cdylib", "lib"]

[dependencies]
solana-program = "2.0.13"
borsh = "1.5.1"
thiserror = "1.0.64"